name: Build and Push Docker Image Latest (Backend)

on:
  push:
    branches-ignore:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Test connection
        run: |
          ip addr
          curl https://${{ secrets.DOCKER_REGISTRY_URL }}/v2/ -v

      - name: Build and Push Docker image
        run: |
          cd ./backend
          docker build . --tag ${{ secrets.DOCKER_REGISTRY_URL }}/isgood-backend:latest
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/isgood-backend:latest
