# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Golang

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Switch to backend folder
      run: cd ./backend && ls -al

    - name: Setup Go 1.19
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Download dependencies
      run: go mod download

    - name: Audit code
      run: |
        go vet ./...
        go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...
        go test -race -vet=off ./...
        go mod verify
      
    - name: Build
      run: CGO_ENABLED=0 GOOS=linux go build -v 
